language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

script:
   - ./gradlew build connectedCheck
jdk:
  - oraclejdk8
